version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py seed &&
             gunicorn residential_parking_permit.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A residential_parking_permit worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    env_file:
      - .env

  beat:
    build: .
    command: celery -A residential_parking_permit beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"